[build]
  base = "frontend"
  command = "ng build && npm run serve:ssr:frontend"
  publish = "dist/browser"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
